# PostgreSQL. Versions 8.2 and up are supported.

development:

  # Connect on a TCP socket. Omitted by default since the client uses a
 
production:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE_NAME']
  pool: 5
  username: ENV['DATABASE_USER']
  url: ENV['DATABASE_URL']
  password: ENV['DATABASE_PASSWORD']
  host: ENV['DATABASE_HOST']